/**
 * cn — className utility wrapping clsx + tailwind-merge.
 *
 * Generated by impeccable Mode C as part of the core component set.
 * Resolves Tailwind class conflicts when consumers pass className overrides
 * (last-class-wins semantics in tailwind-merge).
 *
 * Citations: [docs:tailwindcss], [docs:shadcn-ui] (cn pattern is canon).
 */

import { clsx, type ClassValue } from 'clsx'
import { twMerge } from 'tailwind-merge'

export function cn(...inputs: ClassValue[]): string {
  return twMerge(clsx(inputs))
}
