/**
 * Brand Showcase — Visual contract verifier
 *
 * Auto-generated by add-ui-kit. This page renders every component declared
 * in `brand/brand.json` `component_rules`, plus a typography scale,
 * palette grid, motion samples, and voice copy examples.
 *
 * Purpose:
 *   1. Manual visual diff — verify the generated brand.css matches the
 *      Discovery intent before any other UI is built on top.
 *   2. Automatic Anti-Slop Gate target — el-evaluador may screenshot this
 *      page (via agent-browser) and run image diff vs brand.json claims.
 *   3. Reference for downstream skills (impeccable, ai/ UI generators,
 *      add-* in block D) — they import patterns from sections/ to render
 *      consistently.
 *
 * Citations:
 *   [memory:references#R-005]              — schema source (component_rules)
 *   [memory:CONSTRAINTS.md#R10]            — Brand DNA contract gate
 *   [docs:nextjs] — App Router page in (brand) route group
 *   [docs:tailwindcss] — arbitrary value syntax bg-[var(--color-primary)]
 *   [docs:shadcn-ui] — button/card/input variants reference
 *
 * DO NOT edit hex values inline. All visual values come from brand.css vars.
 */

import type { Metadata } from 'next'
import { ViewportToggle } from './viewport-toggle'
import { GlobalFeedbackButton } from './feedback-panel'
import { PaletteSection } from './sections/palette'
import { TypographySection } from './sections/typography'
import { ButtonsSection } from './sections/buttons'
import { InputsSection } from './sections/inputs'
import { CardsSection } from './sections/cards'
import { BadgesSection } from './sections/badges'
import { AlertsSection } from './sections/alerts'
import { NavigationSection } from './sections/navigation'
import { LoadingSection } from './sections/loading'
import { TabsSection } from './sections/tabs'
import { AvatarsSection } from './sections/avatars'
import { ToastSection } from './sections/toast'
import { EmptyStatesSection } from './sections/empty-states'
import { MotionSection } from './sections/motion'
import { VoiceSection } from './sections/voice'
import { KpiRowPattern } from './sections/saas-patterns/kpi-row'
import { DataTablePattern } from './sections/saas-patterns/data-table'
import { OnboardingPattern } from './sections/saas-patterns/onboarding'
import { SidebarPattern } from './sections/saas-patterns/sidebar'
import { EmptyCompletePattern } from './sections/saas-patterns/empty-complete'
import { AuthFormPattern } from './sections/saas-patterns/auth-form'
import { NavbarPattern } from './sections/saas-patterns/navbar'
import '@/brand/brand.css' // single source of truth — NEVER inline tokens

// Build-time inlined: the skill writes NEXT_PUBLIC_HAS_AGENTATION=true to
// .env.local in Paso 1D when an Agentation toolbar is detected in src/.
const HAS_AGENTATION = process.env.NEXT_PUBLIC_HAS_AGENTATION === 'true'

export const metadata: Metadata = {
  title: 'Brand Showcase — {{ brand.product }}',
  description: 'Visual contract for {{ brand.name }} — generated by add-ui-kit from brand/brand.json',
}

export default function BrandShowcasePage() {
  return (
    <ViewportToggle>
      <main className="min-h-screen bg-[var(--color-surface)] text-[var(--color-text)]">
        <header className="mx-auto max-w-screen-xl px-6 py-[var(--section-y-md)]">
          <p className="font-mono text-xs uppercase tracking-widest text-[var(--color-text-subtle)]">
            Brand DNA Showcase · v1.0.0
          </p>
          <h1 className="mt-3 font-[family-name:var(--font-display)] text-5xl font-bold leading-tight md:text-6xl">
            {{ brand.product }}
          </h1>
          <p className="mt-4 max-w-2xl text-lg leading-[var(--line-height-body)] text-[var(--color-text-muted)]">
            {{ brand.tagline }}
          </p>
          <ShowcaseMeta />
        </header>

        <div className="mx-auto max-w-screen-xl space-y-[var(--section-y-lg)] px-6 pb-[var(--section-y-lg)]">
          <HowToPanel />

          {/* Part 1 — Component vocabulary */}
          <PaletteSection />
          <TypographySection />
          <ButtonsSection />
          <InputsSection />
          <CardsSection />
          <BadgesSection />
          <AlertsSection />
          <NavigationSection />
          <LoadingSection />
          <TabsSection />
          <AvatarsSection />
          <ToastSection />
          <EmptyStatesSection />
          <MotionSection />
          <VoiceSection />

          {/* Part 2 — SaaS Patterns */}
          <div className="border-t border-[var(--color-border)] pt-[var(--section-y-md)]">
            <p className="font-mono text-xs uppercase tracking-widest text-[var(--color-text-subtle)]">
              Part 2
            </p>
            <h2 className="mt-3 font-[family-name:var(--font-display)] text-3xl font-bold leading-tight">
              SaaS Patterns
            </h2>
            <p className="mt-2 max-w-2xl leading-[var(--line-height-body)] text-[var(--color-text-muted)]">
              Composiciones reales — los componentes de arriba ensamblados en los
              layouts que un producto SaaS usa todos los días.
            </p>
          </div>
          <KpiRowPattern />
          <DataTablePattern />
          <OnboardingPattern />
          <SidebarPattern />
          <EmptyCompletePattern />
          <AuthFormPattern />
          <NavbarPattern />
        </div>

        <footer className="border-t border-[var(--color-border)] px-6 py-[var(--space-12)] text-center font-mono text-xs text-[var(--color-text-subtle)]">
          Generated by add-ui-kit · Schema R-005 · Verify against brand.json
        </footer>
      </main>
      <GlobalFeedbackButton />
    </ViewportToggle>
  )
}

/**
 * How-To panel — collapsible (native <details>, open by default, no JS).
 * Two variants gated on HAS_AGENTATION. Concise adaptation of the Forge
 * spec copy ([forge:add-ui-kit/SKILL.md#how-to-panel]); the full prose lives
 * there. CSS-var styling only.
 */
function HowToPanel() {
  return (
    <details
      open
      className="rounded-[var(--radius-md)] border border-[var(--color-border)] bg-[var(--color-surface-elevated)] px-[var(--space-6)] py-[var(--space-4)]"
    >
      <summary className="cursor-pointer font-[family-name:var(--font-display)] text-lg font-semibold text-[var(--color-text)]">
        Cómo mejorar el UI Kit
      </summary>
      <div className="mt-[var(--space-3)] space-y-[var(--space-3)] text-sm leading-[var(--line-height-body)] text-[var(--color-text-muted)]">
        <p>
          Este showcase es la fuente de verdad visual del proyecto. Los agentes de
          Claude Code lo leen antes de crear cualquier componente.
        </p>
        {HAS_AGENTATION ? (
          <>
            <p className="font-medium text-[var(--color-text)]">
              Opción A — Feedback de texto
            </p>
            <ol className="ml-[var(--space-4)] list-decimal space-y-[var(--space-1)]">
              <li>Clic en el ícono de lápiz junto al título de la sección.</li>
              <li>Describe el cambio con precisión.</li>
              <li>Guarda → se escribe en UI_FEEDBACK.md.</li>
            </ol>
            <p className="font-medium text-[var(--color-text)]">
              Opción B — Anotaciones visuales con Agentation (recomendado)
            </p>
            <ol className="ml-[var(--space-4)] list-decimal space-y-[var(--space-1)]">
              <li>Activa la barra de Agentation y haz clic sobre el componente.</li>
              <li>Escribe la anotación y cópiala.</li>
              <li>Pégala en el campo &quot;Anotaciones Agentation&quot; del panel de la sección.</li>
              <li>Guarda → UI_FEEDBACK.md queda con contexto visual preciso.</li>
            </ol>
            <p>
              Al correr <code className="font-mono">/add-ui-kit</code>, Claude lee
              UI_FEEDBACK.md y propone los cambios — las anotaciones le dicen qué
              elemento exacto tocar.
            </p>
          </>
        ) : (
          <>
            <ol className="ml-[var(--space-4)] list-decimal space-y-[var(--space-1)]">
              <li>Encuentra algo que quieras cambiar (un radius, un color, etc.).</li>
              <li>Haz clic en el ícono de lápiz junto al título de esa sección.</li>
              <li>
                Describe el cambio: &quot;el radius de los botones se siente muy
                redondo para un SaaS B2B&quot;.
              </li>
              <li>Guarda → se escribe en UI_FEEDBACK.md.</li>
              <li>
                Vuelve a Claude Code y corre{' '}
                <code className="font-mono">/add-ui-kit</code>.
              </li>
            </ol>
            <p>
              ¿Prefieres marcar directamente sobre los componentes? Instala
              Agentation con <code className="font-mono">/agentation</code> para
              anotar visualmente qué cambiar.
            </p>
          </>
        )}
      </div>
    </details>
  )
}

/**
 * Inline meta-strip — surfaces archetype + posture so el-evaluador can
 * cross-check the rendered showcase against the declared contract without
 * opening brand.json.
 */
function ShowcaseMeta() {
  return (
    <dl className="mt-8 grid grid-cols-2 gap-x-[var(--space-6)] gap-y-[var(--space-3)] font-mono text-xs md:grid-cols-4">
      <div>
        <dt className="text-[var(--color-text-subtle)]">archetype.primary</dt>
        <dd className="text-[var(--color-text)]">{{ archetype.primary }}</dd>
      </div>
      <div>
        <dt className="text-[var(--color-text-subtle)]">archetype.secondary</dt>
        <dd className="text-[var(--color-text)]">{{ archetype.secondary | default: '—' }}</dd>
      </div>
      <div>
        <dt className="text-[var(--color-text-subtle)]">posture.density</dt>
        <dd className="text-[var(--color-text)]">{{ posture.density }} / 5</dd>
      </div>
      <div>
        <dt className="text-[var(--color-text-subtle)]">posture.expression</dt>
        <dd className="text-[var(--color-text)]">{{ posture.expression }} / 5</dd>
      </div>
      <div>
        <dt className="text-[var(--color-text-subtle)]">posture.geometry</dt>
        <dd className="text-[var(--color-text)]">{{ posture.geometry }} / 5</dd>
      </div>
      <div>
        <dt className="text-[var(--color-text-subtle)]">posture.warmth</dt>
        <dd className="text-[var(--color-text)]">{{ posture.warmth }} / 5</dd>
      </div>
      <div>
        <dt className="text-[var(--color-text-subtle)]">posture.editoriality</dt>
        <dd className="text-[var(--color-text)]">{{ posture.editoriality }} / 5</dd>
      </div>
      <div>
        <dt className="text-[var(--color-text-subtle)]">posture.materiality</dt>
        <dd className="text-[var(--color-text)]">{{ posture.materiality }} / 5</dd>
      </div>
    </dl>
  )
}
