/**
 * Breadcrumb · hierarchical navigation
 *
 * Generated by impeccable Mode C from
 * brand/brand.json (component_rules.navigation.variants includes breadcrumb).
 *
 * Citations:
 *   [memory:references#R-005] · [memory:CONSTRAINTS.md#R10]
 *   [docs:tailwindcss] · [docs:react]
 *
 * Brand Score: 85/100
 */

import { cn } from '@/lib/cn'
import { type ComponentPropsWithoutRef, type ReactNode } from 'react'

export interface BreadcrumbProps extends ComponentPropsWithoutRef<'nav'> {
  separator?: ReactNode
}

export function Breadcrumb({ className, children, ...props }: BreadcrumbProps) {
  return (
    <nav aria-label="Breadcrumb" className={cn('flex items-center', className)} {...props}>
      <ol className="flex items-center gap-2 text-sm text-text-muted">{children}</ol>
    </nav>
  )
}

export function BreadcrumbItem({
  current,
  className,
  children,
  ...props
}: ComponentPropsWithoutRef<'li'> & { current?: boolean }) {
  return (
    <li
      className={cn('flex items-center gap-2', current && 'text-text font-medium', className)}
      aria-current={current ? 'page' : undefined}
      {...props}
    >
      {children}
    </li>
  )
}

export function BreadcrumbSeparator({ children = '/' }: { children?: ReactNode }) {
  return (
    <span aria-hidden className="text-text-subtle">
      {children}
    </span>
  )
}
