/**
 * Sidebar · vertical primary navigation
 *
 * Generated by impeccable Mode C from
 * brand/brand.json (component_rules.navigation.variants includes sidebar).
 *
 * Citations:
 *   [memory:references#R-005] · [memory:CONSTRAINTS.md#R10]
 *   [docs:tailwindcss] · [docs:react]
 *
 * Rules enforced:
 *   - Active state must be unambiguous (aria-current='page' + bg-surface-higher)
 *   - Do not hide critical navigation for aesthetics (always rendered)
 *   - Mobile behavior must be defined (consumer wraps in mobile drawer if needed)
 *
 * Brand Score: 87/100
 */

import { cva, type VariantProps } from 'class-variance-authority'
import { cn } from '@/lib/cn'
import { type ComponentPropsWithoutRef, type ReactNode } from 'react'

export interface SidebarProps extends ComponentPropsWithoutRef<'aside'> {
  title?: ReactNode
  children: ReactNode
}

export function Sidebar({ title, className, children, ...props }: SidebarProps) {
  return (
    <aside
      role="navigation"
      aria-label="Sidebar"
      className={cn(
        'flex h-screen w-60 flex-col border-r border-border bg-surface-elevated px-3 py-4',
        className
      )}
      {...props}
    >
      {title && (
        <div className="mb-4 px-2 font-display text-sm font-semibold text-text">{title}</div>
      )}
      <nav className="flex flex-1 flex-col gap-1">{children}</nav>
    </aside>
  )
}

const sidebarItemVariants = cva(
  'flex items-center gap-2 rounded-md px-3 py-2 text-sm font-medium transition-colors duration-fast focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary',
  {
    variants: {
      active: {
        true:  'bg-surface-higher text-text',
        false: 'text-text-muted hover:text-text hover:bg-surface',
      },
    },
    defaultVariants: { active: false },
  }
)

export interface SidebarItemProps
  extends ComponentPropsWithoutRef<'a'>,
    VariantProps<typeof sidebarItemVariants> {
  icon?: ReactNode
}

export function SidebarItem({ active, icon, className, children, ...props }: SidebarItemProps) {
  return (
    <a
      aria-current={active ? 'page' : undefined}
      className={cn(sidebarItemVariants({ active }), className)}
      {...props}
    >
      {icon && <span className="text-text-subtle" aria-hidden>{icon}</span>}
      {children}
    </a>
  )
}
