'use client'

/**
 * Tabs · tab navigation backed by Radix when shadcn detected
 *
 * Generated by impeccable Mode C from
 * brand/brand.json (component_rules.navigation.variants includes tabs).
 *
 * Citations:
 *   [memory:references#R-005] · [memory:CONSTRAINTS.md#R10]
 *   [docs:tailwindcss] · [docs:shadcn-ui] (Radix Tabs) · [docs:react]
 *
 * Brand Score: 88/100
 */

import { cva } from 'class-variance-authority'
import { cn } from '@/lib/cn'
import { type ComponentPropsWithoutRef } from 'react'
import * as TabsPrimitive from '@radix-ui/react-tabs'

const tabsListVariants = cva('inline-flex h-10 items-center justify-start border-b border-border')

const tabsTriggerVariants = cva(
  '-mb-px inline-flex h-10 items-center justify-center px-4 text-sm font-medium text-text-muted transition-colors duration-fast hover:text-text focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary focus-visible:ring-offset-2 focus-visible:ring-offset-surface data-[state=active]:text-text data-[state=active]:border-b-2 data-[state=active]:border-primary disabled:opacity-50 disabled:cursor-not-allowed'
)

export const Tabs = TabsPrimitive.Root

export function TabsList({ className, ...props }: ComponentPropsWithoutRef<typeof TabsPrimitive.List>) {
  return <TabsPrimitive.List className={cn(tabsListVariants(), className)} {...props} />
}

export function TabsTrigger({
  className,
  ...props
}: ComponentPropsWithoutRef<typeof TabsPrimitive.Trigger>) {
  return <TabsPrimitive.Trigger className={cn(tabsTriggerVariants(), className)} {...props} />
}

export function TabsContent({
  className,
  ...props
}: ComponentPropsWithoutRef<typeof TabsPrimitive.Content>) {
  return (
    <TabsPrimitive.Content
      className={cn(
        'mt-4 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary',
        className
      )}
      {...props}
    />
  )
}
