/**
 * Topbar · horizontal utility navigation
 *
 * Generated by impeccable Mode C from
 * brand/brand.json (component_rules.navigation.variants includes topbar).
 *
 * Citations:
 *   [memory:references#R-005] · [memory:CONSTRAINTS.md#R10]
 *   [docs:tailwindcss] · [docs:react]
 *
 * Brand Score: 90/100
 */

import { cn } from '@/lib/cn'
import { type ComponentPropsWithoutRef, type ReactNode } from 'react'

export interface TopbarProps extends ComponentPropsWithoutRef<'header'> {
  brand?: ReactNode
  actions?: ReactNode
}

export function Topbar({ brand, actions, className, children, ...props }: TopbarProps) {
  return (
    <header
      role="banner"
      className={cn(
        'flex h-14 items-center justify-between gap-4 border-b border-border bg-surface px-4',
        className
      )}
      {...props}
    >
      {brand && (
        <div className="flex items-center gap-2 font-display font-semibold text-text">{brand}</div>
      )}
      <nav role="navigation" aria-label="Topbar" className="flex items-center gap-1">
        {children}
      </nav>
      {actions && <div className="flex items-center gap-2">{actions}</div>}
    </header>
  )
}
