/**
 * Motion System — typed canonical animations
 *
 * Auto-generated by add-ui-kit from brand/brand.json `motion`.
 * Single source of truth for animation in the project. Every component
 * (showcase + impeccable-generated + ai/ UI) imports presets from here —
 * NEVER hardcodes durations or easing curves inline.
 *
 * Durations live as CSS vars in brand.css (--motion-duration-*). This module
 * exposes them as typed semantic presets so TSX gets autocomplete + the
 * compiler catches typos. Values stay 1:1 with brand.json.motion.durations_ms.
 *
 * Exports: DURATION (tiers), EASING (curves), MOTION (animate-in presets),
 * tw (Tailwind transition shorthands), SAFE / UNSAFE (animatable property
 * allow/deny lists enforced by the Anti-Slop Gate), and transition() helper.
 *
 * Citations:
 *   [memory:references#R-005]   — schema source (motion section)
 *   [memory:CONSTRAINTS.md#R10] — Brand DNA contract gate
 *   [docs:tailwindcss]          — animate-in / data-state utilities (tailwindcss-animate)
 *
 * Respects prefers-reduced-motion: brand.css zeroes the duration vars under
 * the media query, so every preset below degrades to instant automatically.
 */

/** Typed durations (ms) — mirror brand.json.motion.durations_ms 1:1. */
export const DURATION = {
  instant: 80,
  fast: 140,
  base: 220,
  slow: 320,
} as const

export type DurationToken = keyof typeof DURATION

/**
 * Easing curves — semantic set. `default` is derived from
 * motion.energy=precise and mirrors brand.css --motion-easing 1:1;
 * the enter/exit/spring curves are canonical fixed values shared across the app.
 * Use `EASING.default` for most interactions; `EASING.spring` RARELY (delight only).
 */
export const EASING = {
  /** Default for most interactions — snaps into position, smooth stop. */
  default: 'cubic-bezier(0.4, 0, 0.2, 1)',
  /** Elements entering the screen. */
  enter: 'cubic-bezier(0, 0, 0.2, 1)',
  /** Elements leaving the screen. */
  exit: 'cubic-bezier(0.4, 0, 1, 1)',
  /** Subtle overshoot — use RARELY, only for delightful micro-interactions. */
  spring: 'cubic-bezier(0.34, 1.56, 0.64, 1)',
} as const

export type EasingToken = keyof typeof EASING

/**
 * Semantic animation presets — Tailwind class strings using the CSS-var
 * durations. Use these instead of ad-hoc `animate-*` combos so the whole app
 * shares one motion vocabulary.
 *
 * Requires `tailwindcss-animate` (shadcn default). If absent, add-ui-kit's
 * find-docs step confirms availability before emitting these.
 */
export const MOTION = {
  /** List items, cards entering a view. */
  fadeInUp: 'animate-in fade-in slide-in-from-bottom-2 duration-[var(--motion-duration-base)]',
  /** Overlays, tooltips, subtle reveals. */
  fadeIn: 'animate-in fade-in duration-[var(--motion-duration-fast)]',
  /** Modals, dialogs. */
  zoomIn: 'animate-in zoom-in-95 fade-in duration-[var(--motion-duration-base)]',
  /** Drawers, side panels, mobile nav sheets. */
  slideInRight: 'animate-in slide-in-from-right duration-[var(--motion-duration-slow)]',
  /** Exit for toasts / dismissables. */
  slideOutRight: 'animate-out slide-out-to-right fade-out duration-[var(--motion-duration-fast)]',
} as const

export type MotionPreset = keyof typeof MOTION

/**
 * Tailwind shorthand classes for the most common transition intents. Durations
 * resolve to the CSS-var tiers (so prefers-reduced-motion zeroes them for free);
 * easing curves are emitted as arbitrary values since they have no CSS var.
 * Only transform/opacity/color/etc. are transitioned — never layout properties.
 */
export const tw = {
  /** Hover / focus state changes — color + bg + border only. */
  hover:
    'transition-[color,background-color,border-color] duration-[var(--motion-duration-fast)] ease-[var(--motion-easing)]',
  /** Element entering the screen. */
  enter:
    'transition-[transform,opacity] duration-[var(--motion-duration-base)] ease-[cubic-bezier(0,0,0.2,1)]',
  /** Element leaving the screen. */
  exit: 'transition-[transform,opacity] duration-[var(--motion-duration-fast)] ease-[cubic-bezier(0.4,0,1,1)]',
  /** Drawers, side panels, mobile nav sheets — transform only. */
  drawer: 'transition-transform duration-[var(--motion-duration-slow)] ease-[var(--motion-easing)]',
  /** Modals, dialogs — transform + opacity. */
  modal:
    'transition-[transform,opacity] duration-[var(--motion-duration-base)] ease-[var(--motion-easing)]',
} as const

export type TwToken = keyof typeof tw

/**
 * Properties that are GPU-cheap to animate (composite/paint only). The
 * Anti-Slop Gate verifies every transition target stays inside this set.
 */
export const SAFE = [
  'transform',
  'opacity',
  'filter',
  'color',
  'background-color',
  'border-color',
  'box-shadow',
] as const

/**
 * Layout properties — NEVER animate. Each triggers reflow on every frame and
 * kills performance. el-evaluador flags any transition that touches these.
 */
export const UNSAFE = [
  'width',
  'height',
  'padding',
  'margin',
  'top',
  'left',
  'right',
  'bottom',
  'max-height',
] as const

/** Inline style helper when a one-off transition needs the canonical curve. */
export function transition(
  property: string,
  token: DurationToken = 'fast',
  easing: EasingToken = 'default',
): string {
  return `${property} ${DURATION[token]}ms ${EASING[easing]}`
}
