/**
 * src/shared/components/ui — barrel re-export.
 *
 * Generated by impeccable Mode C from brand/brand.json.
 *
 * Citations: [memory:references#R-005] · [memory:CONSTRAINTS.md#R10]
 */

export { Button } from './Button'
export type { ButtonProps, ButtonVariant, ButtonSize } from './Button'

export { Card, CardMetricLabel, CardMetricValue, CardMetricDelta } from './Card'
export type { CardProps, CardVariant } from './Card'

export { Input, SearchInput } from './Form'
export type { InputProps, SearchInputProps } from './Form'
export { Textarea } from './Form'
export type { TextareaProps } from './Form'
export { Select } from './Form'
export type { SelectProps } from './Form'

export { Modal, ConfirmModal } from './Modal'
export type { ModalProps, ConfirmModalProps, ModalVariant } from './Modal'

export { Sidebar, SidebarItem } from './Navigation'
export type { SidebarProps, SidebarItemProps } from './Navigation'
export { Topbar } from './Navigation'
export type { TopbarProps } from './Navigation'
export { Tabs, TabsList, TabsTrigger, TabsContent } from './Navigation'
export { Breadcrumb, BreadcrumbItem, BreadcrumbSeparator } from './Navigation'
export type { BreadcrumbProps } from './Navigation'

// Mode B derived components
export { DataTable } from './DataTable'
export type { DataTableProps, DataTableColumn } from './DataTable'

// Shared types
export type { Sizes, WithIcons, AsProp, PolymorphicProps } from './types'
