/**
 * Shared utility types for src/shared/components/ui.
 *
 * Generated by impeccable Mode C from brand/brand.json.
 *
 * Citations: [memory:references#R-005] · [memory:CONSTRAINTS.md#R10] · [docs:react]
 */

import type { ComponentPropsWithoutRef, ElementType, ReactNode } from 'react'

export type Sizes = 'sm' | 'md' | 'lg'

export type WithIcons<T = unknown> = T & {
  iconLeft?: ReactNode
  iconRight?: ReactNode
}

export type AsProp<C extends ElementType> = { as?: C }

export type PolymorphicProps<C extends ElementType, P = {}> = AsProp<C> &
  P &
  Omit<ComponentPropsWithoutRef<C>, keyof (AsProp<C> & P)>
