/**
 * Showcase Feedback Actions — Server Actions backing the in-page feedback loop.
 *
 * Auto-generated by add-ui-kit. The showcase is the visual source of truth;
 * this module lets a human (or an Agentation-assisted human) write change
 * requests straight into `UI_FEEDBACK.md` at the project root. On the next
 * `/add-ui-kit` run the skill reads that file and proposes the specific token
 * edits — closing the loop without leaving the browser.
 *
 * Why a flat markdown file (not a DB): the consumer is Claude Code reading the
 * repo, and the human can hand-edit it in their editor. process.cwd() resolves
 * to the project root in Next dev/build, so the file sits next to brand.json.
 *
 * Entries are append-only; clearFeedback() resets to the header so the file is
 * never deleted (the skill can always find it).
 *
 * Citations:
 *   [memory:references#R-005]   — schema source (Discovery intent these notes feed back into)
 *   [memory:CONSTRAINTS.md#R10] — Brand DNA contract gate (feedback re-tunes the contract)
 *   [docs:nextjs]               — Server Actions ('use server', App Router)
 */

'use server'

import { appendFile, readFile, writeFile } from 'node:fs/promises'
import { existsSync } from 'node:fs'
import { join } from 'node:path'

const FEEDBACK_FILE = join(process.cwd(), 'UI_FEEDBACK.md')

const HEADER =
  '# UI Feedback\n\n' +
  'Notas para mejorar el Component Showcase.\n' +
  'Claude Code lee este archivo en el próximo /add-ui-kit y propone los cambios.\n\n' +
  '---\n'

/**
 * Append one feedback entry for a showcase section. Creates the file with the
 * header if it does not exist yet. `agentationNotes` is optional — when present
 * (pasted from the Agentation toolbar) it is stored as a fenced block so the
 * visual context survives verbatim.
 */
export async function saveFeedback(
  section: string,
  feedback: string,
  agentationNotes?: string,
): Promise<{ ok: true }> {
  if (!existsSync(FEEDBACK_FILE)) {
    await writeFile(FEEDBACK_FILE, HEADER, 'utf-8')
  }

  const timestamp = new Date().toLocaleString('es-MX', {
    timeZone: 'America/Mexico_City',
    dateStyle: 'short',
    timeStyle: 'short',
  })

  const agentationBlock = agentationNotes?.trim()
    ? `\n**Anotaciones Agentation:**\n\`\`\`\n${agentationNotes.trim()}\n\`\`\`\n`
    : ''

  const entry =
    `\n## ${section}\n` +
    `**Fecha:** ${timestamp}  \n` +
    `**Feedback:** ${feedback.trim()}${agentationBlock}\n` +
    `---\n`

  await appendFile(FEEDBACK_FILE, entry, 'utf-8')

  return { ok: true }
}

/**
 * Read the current UI_FEEDBACK.md so the global panel can show what is queued
 * for the next /add-ui-kit run. Returns the header alone if nothing was saved.
 */
export async function readFeedback(): Promise<string> {
  if (!existsSync(FEEDBACK_FILE)) {
    return HEADER
  }
  return readFile(FEEDBACK_FILE, 'utf-8')
}

/** Reset UI_FEEDBACK.md to the header — wipes all queued feedback. */
export async function clearFeedback(): Promise<{ ok: true }> {
  await writeFile(FEEDBACK_FILE, HEADER, 'utf-8')
  return { ok: true }
}
