/**
 * Showcase Feedback Panel — the in-page feedback loop UI (Agentation-aware).
 *
 * Auto-generated by add-ui-kit. Three pieces wire the showcase to the server
 * actions in `./actions`:
 *   - FeedbackButton       — the per-section pencil affordance (hover-revealed)
 *   - FeedbackForm         — the inline editor it expands into (NOT a modal)
 *   - GlobalFeedbackButton — the floating button + right drawer that lists
 *                            everything queued in UI_FEEDBACK.md
 *
 * Agentation awareness: when NEXT_PUBLIC_HAS_AGENTATION === 'true' (the skill
 * sets this in Step 1D when it detects the Agentation toolbar), the form shows
 * a second field for pasting visual annotations so Claude Code gets the exact
 * element context on the next /add-ui-kit run.
 *
 * Anti-Slop notes for el-evaluador:
 *   - No hex / no Tailwind palette classes — every visual value is a CSS var.
 *   - Animation is opacity / transform / color / background-color only
 *     (drawer enters via slide-in-from-right = transform; never width/left).
 *   - Icon-only triggers carry aria-label; the textarea has a real <label>;
 *     focus-visible rings are present; saving buttons are disabled + aria-busy.
 *
 * Citations:
 *   [memory:references#R-005]   — Brand DNA contract these notes re-tune
 *   [memory:CONSTRAINTS.md#R10] — Brand DNA contract gate
 *   [docs:nextjs]               — Server Actions invoked from a Client Component
 *   [docs:tailwindcss]          — arbitrary value syntax bg-[var(--color-primary)]
 *   [docs:shadcn-ui]            — button/input/sheet variant reference
 */

'use client'

import { useEffect, useRef, useState } from 'react'
import { Check, Loader2, MessageSquare, Pencil, RotateCcw, Trash2, X } from 'lucide-react'
import { clearFeedback, readFeedback, saveFeedback } from './actions'

/**
 * Read once at module load. The skill writes NEXT_PUBLIC_HAS_AGENTATION=true to
 * .env.local when Agentation is installed (Step 1D), so this is inlined at build
 * time and the Agentation field only renders where it makes sense.
 */
const HAS_AGENTATION = process.env.NEXT_PUBLIC_HAS_AGENTATION === 'true'

const SAVED_AUTO_CLOSE_MS = 1500

type FormStatus = 'idle' | 'saving' | 'saved' | 'error'

/* ------------------------------------------------------------------ */
/* FeedbackButton — per-section pencil, revealed on section hover.     */
/* Render inline next to a section <h2>. The section header must carry */
/* the `group` class for the hover reveal to work.                     */
/* ------------------------------------------------------------------ */

export function FeedbackButton({ section }: { section: string }) {
  const [open, setOpen] = useState(false)

  return (
    <span className="relative inline-flex items-center align-middle">
      <button
        type="button"
        onClick={() => setOpen((v) => !v)}
        aria-label={`Dar feedback sobre la sección ${section}`}
        aria-expanded={open}
        className="ml-[var(--space-2)] inline-flex h-7 w-7 items-center justify-center rounded-[var(--radius-sm)] text-[var(--color-text-subtle)] opacity-0 transition-opacity duration-[150ms] hover:bg-[var(--color-surface-elevated)] hover:text-[var(--color-text)] focus-visible:opacity-100 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[var(--color-primary)] group-hover:opacity-100"
      >
        <Pencil className="h-4 w-4" aria-hidden />
      </button>

      {open ? (
        <FeedbackForm
          section={section}
          hasAgentation={HAS_AGENTATION}
          onClose={() => setOpen(false)}
        />
      ) : null}
    </span>
  )
}

/* ------------------------------------------------------------------ */
/* FeedbackForm — inline editor expanded under a section title.        */
/* ------------------------------------------------------------------ */

export function FeedbackForm({
  section,
  hasAgentation = false,
  onClose,
}: {
  section: string
  hasAgentation?: boolean
  onClose: () => void
}) {
  const [feedback, setFeedback] = useState('')
  const [agentationNotes, setAgentationNotes] = useState('')
  const [status, setStatus] = useState<FormStatus>('idle')
  const [errorMsg, setErrorMsg] = useState('')

  const feedbackId = `feedback-${section}`
  const agentationId = `agentation-${section}`
  const saving = status === 'saving'

  // Auto-close shortly after a successful save so the affordance gets out of
  // the way once the note is on disk.
  useEffect(() => {
    if (status !== 'saved') return
    const t = setTimeout(onClose, SAVED_AUTO_CLOSE_MS)
    return () => clearTimeout(t)
  }, [status, onClose])

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault()
    if (!feedback.trim() || saving) return
    setStatus('saving')
    setErrorMsg('')
    try {
      await saveFeedback(section, feedback, hasAgentation ? agentationNotes : undefined)
      setStatus('saved')
    } catch (err) {
      setErrorMsg(err instanceof Error ? err.message : 'No se pudo guardar el feedback.')
      setStatus('error')
    }
  }

  return (
    <form
      onSubmit={handleSubmit}
      className="absolute z-20 mt-[var(--space-2)] w-[min(28rem,calc(100vw-2rem))] space-y-[var(--space-3)] rounded-[var(--radius-md)] border border-[var(--color-border)] bg-[var(--color-surface-elevated)] p-[var(--space-4)] text-left shadow-lg"
    >
      <div>
        <label
          htmlFor={feedbackId}
          className="block text-xs font-medium uppercase tracking-widest text-[var(--color-text-subtle)]"
        >
          Feedback · {section}
        </label>
        <textarea
          id={feedbackId}
          autoFocus
          rows={3}
          value={feedback}
          onChange={(e) => setFeedback(e.target.value)}
          disabled={saving}
          placeholder="¿Qué cambiarías en esta sección?"
          className="mt-[var(--space-2)] block w-full resize-none rounded-[var(--radius-sm)] border border-[var(--color-border)] bg-[var(--color-surface)] px-[var(--space-3)] py-[var(--space-2)] text-sm leading-[var(--line-height-body)] text-[var(--color-text)] placeholder:text-[var(--color-text-subtle)] focus:border-[var(--color-primary)] focus:outline-none focus:ring-2 focus:ring-[var(--color-primary)]"
        />
      </div>

      {hasAgentation ? (
        <div>
          <label
            htmlFor={agentationId}
            className="block text-xs font-medium text-[var(--color-text-muted)]"
          >
            Anotaciones Agentation (opcional)
          </label>
          <textarea
            id={agentationId}
            rows={2}
            value={agentationNotes}
            onChange={(e) => setAgentationNotes(e.target.value)}
            disabled={saving}
            placeholder="Pega aquí las anotaciones de Agentation..."
            className="mt-[var(--space-2)] block w-full resize-none rounded-[var(--radius-sm)] border border-[var(--color-border)] bg-[var(--color-surface)] px-[var(--space-3)] py-[var(--space-2)] font-mono text-xs leading-[var(--line-height-body)] text-[var(--color-text)] placeholder:text-[var(--color-text-subtle)] focus:border-[var(--color-primary)] focus:outline-none focus:ring-2 focus:ring-[var(--color-primary)]"
          />
        </div>
      ) : null}

      {status === 'error' ? (
        <p
          role="alert"
          className="flex items-center gap-[var(--gap-xs)] text-xs text-[var(--color-danger)]"
        >
          {errorMsg || 'No se pudo guardar el feedback.'}
        </p>
      ) : null}

      <div className="flex items-center justify-end gap-[var(--gap-xs)]">
        {status === 'saved' ? (
          <span className="mr-auto flex items-center gap-[var(--gap-xs)] text-xs text-[var(--color-success)]">
            <Check className="h-4 w-4" aria-hidden />
            Guardado en UI_FEEDBACK.md
          </span>
        ) : null}

        <button
          type="button"
          onClick={onClose}
          disabled={saving}
          className="rounded-[var(--radius-sm)] px-[var(--space-3)] py-[var(--space-1)] text-sm font-medium text-[var(--color-text-muted)] transition-colors duration-[var(--motion-duration-fast)] hover:text-[var(--color-text)] focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[var(--color-primary)] disabled:opacity-50"
        >
          Cancelar
        </button>

        {status === 'error' ? (
          <button
            type="submit"
            className="inline-flex items-center gap-[var(--gap-xs)] rounded-[var(--radius-sm)] bg-[var(--color-primary)] px-[var(--space-4)] py-[var(--space-1)] text-sm font-semibold text-white transition-colors duration-[var(--motion-duration-fast)] hover:opacity-90 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[var(--color-primary)]"
          >
            <RotateCcw className="h-4 w-4" aria-hidden />
            Reintentar
          </button>
        ) : (
          <button
            type="submit"
            disabled={saving || status === 'saved' || !feedback.trim()}
            aria-busy={saving}
            className="inline-flex items-center gap-[var(--gap-xs)] rounded-[var(--radius-sm)] bg-[var(--color-primary)] px-[var(--space-4)] py-[var(--space-1)] text-sm font-semibold text-white transition-colors duration-[var(--motion-duration-fast)] hover:opacity-90 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[var(--color-primary)] disabled:cursor-not-allowed disabled:opacity-50"
          >
            {saving ? <Loader2 className="h-4 w-4 animate-spin" aria-hidden /> : null}
            {saving ? 'Guardando…' : 'Guardar'}
          </button>
        )}
      </div>
    </form>
  )
}

/* ------------------------------------------------------------------ */
/* GlobalFeedbackButton — floating trigger + right drawer listing      */
/* the contents of UI_FEEDBACK.md.                                     */
/* ------------------------------------------------------------------ */

export function GlobalFeedbackButton() {
  const [open, setOpen] = useState(false)
  const [content, setContent] = useState('')
  const [loading, setLoading] = useState(false)
  const [confirmingClear, setConfirmingClear] = useState(false)
  const closeRef = useRef<HTMLButtonElement>(null)

  // Load (and refresh) the file each time the drawer opens.
  useEffect(() => {
    if (!open) return
    let active = true
    // Loading flag for an async fetch triggered by this effect (the fetch
    // itself resolves via callback, per the rule's own accepted pattern).
    // eslint-disable-next-line react-hooks/set-state-in-effect
    setLoading(true)
    readFeedback()
      .then((text) => {
        if (active) setContent(text)
      })
      .finally(() => {
        if (active) setLoading(false)
      })
    closeRef.current?.focus()
    return () => {
      active = false
    }
  }, [open])

  // Esc closes the drawer.
  useEffect(() => {
    if (!open) return
    function onKey(e: KeyboardEvent) {
      if (e.key === 'Escape') closeDrawer()
    }
    window.addEventListener('keydown', onKey)
    return () => window.removeEventListener('keydown', onKey)
  }, [open])

  function closeDrawer() {
    setOpen(false)
    setConfirmingClear(false)
  }

  async function handleClear() {
    await clearFeedback()
    const text = await readFeedback()
    setContent(text)
    setConfirmingClear(false)
  }

  return (
    <>
      <button
        type="button"
        onClick={() => setOpen(true)}
        className="fixed bottom-4 right-4 z-30 inline-flex items-center gap-[var(--gap-xs)] rounded-[var(--radius-md)] border border-[var(--color-border)] bg-[var(--color-surface-elevated)] px-[var(--space-4)] py-[var(--space-2)] text-sm font-medium text-[var(--color-text)] shadow-lg transition-colors duration-[var(--motion-duration-fast)] hover:bg-[var(--color-surface)] focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[var(--color-primary)]"
      >
        <MessageSquare className="h-5 w-5" aria-hidden />
        Ver feedback
      </button>

      {open ? (
        <div
          role="dialog"
          aria-modal="true"
          aria-labelledby="global-feedback-title"
          className="fixed inset-0 z-40 flex justify-end"
        >
          {/* Scrim */}
          <button
            type="button"
            aria-label="Cerrar panel de feedback"
            onClick={closeDrawer}
            className="absolute inset-0 bg-black/60 animate-in motion-reduce:animate-none fade-in duration-[var(--motion-duration-fast)]"
          />

          {/* Drawer */}
          <aside className="relative flex h-full w-[min(28rem,100vw)] flex-col border-l border-[var(--color-border)] bg-[var(--color-surface)] shadow-2xl animate-in motion-reduce:animate-none slide-in-from-right duration-[var(--motion-duration-slow)]">
            <header className="flex items-center justify-between border-b border-[var(--color-border)] px-[var(--space-6)] py-[var(--space-4)]">
              <h2
                id="global-feedback-title"
                className="font-[family-name:var(--font-display)] text-lg font-semibold text-[var(--color-text)]"
              >
                Feedback guardado
              </h2>
              <button
                ref={closeRef}
                type="button"
                onClick={closeDrawer}
                aria-label="Cerrar panel de feedback"
                className="inline-flex h-8 w-8 items-center justify-center rounded-[var(--radius-sm)] text-[var(--color-text-muted)] transition-colors duration-[var(--motion-duration-fast)] hover:bg-[var(--color-surface-elevated)] hover:text-[var(--color-text)] focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[var(--color-primary)]"
              >
                <X className="h-5 w-5" aria-hidden />
              </button>
            </header>

            <div className="flex-1 overflow-y-auto px-[var(--space-6)] py-[var(--space-4)]">
              {loading ? (
                <p className="flex items-center gap-[var(--gap-xs)] text-sm text-[var(--color-text-subtle)]">
                  <Loader2 className="h-4 w-4 animate-spin" aria-hidden />
                  Cargando…
                </p>
              ) : (
                <pre className="whitespace-pre-wrap break-words font-mono text-xs leading-[var(--line-height-body)] text-[var(--color-text-muted)]">
                  {content}
                </pre>
              )}
            </div>

            <footer className="space-y-[var(--space-3)] border-t border-[var(--color-border)] px-[var(--space-6)] py-[var(--space-4)]">
              <p className="text-xs text-[var(--color-text-subtle)]">
                Corre{' '}
                <code className="font-mono text-[var(--color-text-muted)]">/add-ui-kit</code> en
                Claude Code para incorporar estos cambios.
              </p>

              {confirmingClear ? (
                <div className="space-y-[var(--space-2)] rounded-[var(--radius-sm)] border border-[var(--color-danger)] bg-[var(--color-surface-elevated)] p-[var(--space-3)]">
                  <p className="text-xs text-[var(--color-text)]">
                    ¿Seguro? Esto borra todo el feedback guardado.
                  </p>
                  <div className="flex justify-end gap-[var(--gap-xs)]">
                    <button
                      type="button"
                      onClick={() => setConfirmingClear(false)}
                      className="rounded-[var(--radius-sm)] px-[var(--space-3)] py-[var(--space-1)] text-sm font-medium text-[var(--color-text-muted)] transition-colors duration-[var(--motion-duration-fast)] hover:text-[var(--color-text)] focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[var(--color-primary)]"
                    >
                      Cancelar
                    </button>
                    <button
                      type="button"
                      onClick={handleClear}
                      className="inline-flex items-center gap-[var(--gap-xs)] rounded-[var(--radius-sm)] bg-[var(--color-danger)] px-[var(--space-4)] py-[var(--space-1)] text-sm font-semibold text-white transition-colors duration-[var(--motion-duration-fast)] hover:opacity-90 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[var(--color-danger)]"
                    >
                      <Trash2 className="h-4 w-4" aria-hidden />
                      Sí, limpiar
                    </button>
                  </div>
                </div>
              ) : (
                <button
                  type="button"
                  onClick={() => setConfirmingClear(true)}
                  className="inline-flex items-center gap-[var(--gap-xs)] rounded-[var(--radius-sm)] border border-[var(--color-danger)] px-[var(--space-4)] py-[var(--space-2)] text-sm font-medium text-[var(--color-danger)] transition-colors duration-[var(--motion-duration-fast)] hover:bg-[var(--color-danger)]/10 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[var(--color-danger)]"
                >
                  <Trash2 className="h-4 w-4" aria-hidden />
                  Limpiar todo el feedback
                </button>
              )}
            </footer>
          </aside>
        </div>
      ) : null}
    </>
  )
}
