/**
 * Select · variant: select (single)
 *
 * Generated by impeccable Mode C from
 * brand/brand.json (component_rules.form).
 *
 * Citations:
 *   [memory:references#R-005] · [memory:CONSTRAINTS.md#R10]
 *   [memory:lessons#L-003] · [docs:tailwindcss] · [docs:shadcn-ui] · [docs:react]
 *
 * Brand Score: 85/100
 */

import { cva, type VariantProps } from 'class-variance-authority'
import { cn } from '@/lib/cn'
import { forwardRef, useId, type ComponentPropsWithoutRef } from 'react'

const selectVariants = cva(
  'block w-full rounded-md border border-border bg-surface px-3 py-2 text-sm text-text transition-colors duration-fast focus:border-primary focus:outline-none focus:ring-2 focus:ring-primary disabled:opacity-50 disabled:cursor-not-allowed aria-[invalid=true]:border-danger',
  {
    variants: {
      tone: { neutral: '', error: 'border-danger ring-danger' },
    },
    defaultVariants: { tone: 'neutral' },
  }
)

export interface SelectProps
  extends ComponentPropsWithoutRef<'select'>,
    VariantProps<typeof selectVariants> {
  label?: string
  hint?: string
  error?: string
}

export const Select = forwardRef<HTMLSelectElement, SelectProps>(function Select(
  { className, tone, label, hint, error, id, required, children, ...props },
  ref
) {
  const generatedId = useId()
  const localId = id ?? generatedId
  const describedBy = error ? `${localId}-error` : hint ? `${localId}-hint` : undefined
  return (
    <div className="space-y-1">
      {label && (
        <label htmlFor={localId} className="block text-sm font-medium text-text">
          {label}
          {required && <span className="ml-0.5 text-danger" aria-hidden>*</span>}
        </label>
      )}
      <select
        ref={ref}
        id={localId}
        className={cn(selectVariants({ tone: error ? 'error' : tone }), className)}
        aria-invalid={Boolean(error) || undefined}
        aria-describedby={describedBy}
        required={required}
        {...props}
      >
        {children}
      </select>
      {error ? (
        <p id={`${localId}-error`} role="alert" className="text-xs text-danger">
          {error}
        </p>
      ) : hint ? (
        <p id={`${localId}-hint`} className="text-xs text-text-subtle">
          {hint}
        </p>
      ) : null}
    </div>
  )
})
