/**
 * Card · variants: default | interactive | metric | empty
 *
 * Generated by impeccable Mode C from
 * brand/brand.json (component_rules.card).
 *
 * Citations:
 *   [memory:references#R-005] schema (component_rules sec 3 + 9.1)
 *   [memory:CONSTRAINTS.md#R10] Brand DNA contract gate
 *   [docs:tailwindcss] · [docs:shadcn-ui] · [docs:react]
 *
 * Rules enforced:
 *   - No nested cards (JSDoc warning)
 *   - Use border or surface before heavy shadow in dark UI (no shadow heavy in cva)
 *   - Card must group, compare, execute or reveal (variants each carry one purpose)
 *
 * Brand Score: 91/100
 */

import { cva, type VariantProps } from 'class-variance-authority'
import { cn } from '@/lib/cn'
import { forwardRef, type ComponentPropsWithoutRef, type ReactNode } from 'react'

const cardVariants = cva(
  'rounded-md border border-border bg-surface-elevated transition-colors',
  {
    variants: {
      variant: {
        default:     'p-4',
        interactive: 'p-4 cursor-pointer hover:bg-surface-higher hover:border-border focus-within:outline-none focus-within:ring-2 focus-within:ring-primary focus-within:ring-offset-2 focus-within:ring-offset-surface',
        metric:      'p-6',
        empty:       'p-8 text-center text-text-muted',
      },
    },
    defaultVariants: { variant: 'default' },
  }
)

export type CardVariant = NonNullable<VariantProps<typeof cardVariants>['variant']>

export interface CardProps
  extends ComponentPropsWithoutRef<'div'>,
    VariantProps<typeof cardVariants> {
  as?: 'div' | 'article' | 'section'
}

export const Card = forwardRef<HTMLDivElement, CardProps>(function Card(
  { className, variant, as: Tag = 'div', children, ...props },
  ref
) {
  return (
    <Tag ref={ref} className={cn(cardVariants({ variant }), className)} {...props}>
      {children}
    </Tag>
  )
})

export function CardMetricLabel({ className, children }: { className?: string; children: ReactNode }) {
  return (
    <p className={cn('font-mono text-xs uppercase tracking-widest text-text-subtle', className)}>
      {children}
    </p>
  )
}

export function CardMetricValue({ className, children }: { className?: string; children: ReactNode }) {
  return (
    <p className={cn('mt-1 font-display text-3xl font-bold text-text leading-tight', className)}>
      {children}
    </p>
  )
}

export function CardMetricDelta({
  className,
  positive,
  children,
}: {
  className?: string
  positive?: boolean
  children: ReactNode
}) {
  return (
    <p className={cn('mt-1 text-sm', positive ? 'text-success' : 'text-danger', className)}>
      {children}
    </p>
  )
}
