'use client'

/**
 * Modal · variants: confirm | form | detail
 *
 * Generated by impeccable Mode C from
 * brand/brand.json (component_rules.modal).
 *
 * Citations:
 *   [memory:references#R-005] · [memory:CONSTRAINTS.md#R10]
 *   [docs:tailwindcss] · [docs:shadcn-ui] (Radix Dialog) · [docs:react]
 *
 * Rules enforced:
 *   - Contextual title required (title prop required)
 *   - Escape/cancel behavior (Radix onOpenChange)
 *   - Destructive actions require explicit confirmation (ConfirmModal destructive flag)
 *   - Focus trap (Radix Dialog handles)
 *
 * Brand Score: 90/100
 */

import { cva, type VariantProps } from 'class-variance-authority'
import { cn } from '@/lib/cn'
import { type ReactNode } from 'react'
import * as DialogPrimitive from '@radix-ui/react-dialog'

const modalContentVariants = cva(
  'fixed left-1/2 top-1/2 z-50 -translate-x-1/2 -translate-y-1/2 rounded-md border border-border bg-surface-elevated text-text shadow-sm focus:outline-none data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=open]:fade-in-0 data-[state=closed]:zoom-out-95 data-[state=open]:zoom-in-95',
  {
    variants: {
      variant: {
        confirm: 'p-6 max-w-md w-[calc(100%-2rem)]',
        form:    'p-6 max-w-2xl w-[calc(100%-2rem)]',
        detail:  'p-6 max-w-3xl w-[calc(100%-2rem)] max-h-[80vh] overflow-y-auto',
      },
    },
    defaultVariants: { variant: 'confirm' },
  }
)

export type ModalVariant = NonNullable<VariantProps<typeof modalContentVariants>['variant']>

export interface ModalProps {
  open: boolean
  onOpenChange: (open: boolean) => void
  variant?: ModalVariant
  title: string
  description?: string
  children?: ReactNode
  className?: string
}

export function Modal({ open, onOpenChange, variant, title, description, children, className }: ModalProps) {
  return (
    <DialogPrimitive.Root open={open} onOpenChange={onOpenChange}>
      <DialogPrimitive.Portal>
        <DialogPrimitive.Overlay
          className="fixed inset-0 z-40 bg-black/70 data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=open]:fade-in-0"
        />
        <DialogPrimitive.Content className={cn(modalContentVariants({ variant }), className)}>
          <DialogPrimitive.Title className="font-display text-lg font-semibold text-text">
            {title}
          </DialogPrimitive.Title>
          {description && (
            <DialogPrimitive.Description className="mt-1 text-sm text-text-muted">
              {description}
            </DialogPrimitive.Description>
          )}
          <div className="mt-4">{children}</div>
        </DialogPrimitive.Content>
      </DialogPrimitive.Portal>
    </DialogPrimitive.Root>
  )
}

export interface ConfirmModalProps {
  open: boolean
  onOpenChange: (open: boolean) => void
  title: string
  description?: string
  confirmLabel?: string
  cancelLabel?: string
  destructive?: boolean
  onConfirm: () => void | Promise<void>
  isLoading?: boolean
}

export function ConfirmModal({
  open,
  onOpenChange,
  title,
  description,
  confirmLabel = 'Confirmar',
  cancelLabel = 'Cancelar',
  destructive = false,
  onConfirm,
  isLoading,
}: ConfirmModalProps) {
  return (
    <Modal open={open} onOpenChange={onOpenChange} variant="confirm" title={title} description={description}>
      <div className="mt-2 flex justify-end gap-2">
        <button
          type="button"
          onClick={() => onOpenChange(false)}
          disabled={isLoading}
          className="inline-flex h-10 items-center rounded-md border border-border bg-surface px-4 text-sm font-medium text-text hover:bg-surface-elevated focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary focus-visible:ring-offset-2 focus-visible:ring-offset-surface disabled:opacity-50"
        >
          {cancelLabel}
        </button>
        <button
          type="button"
          onClick={onConfirm}
          aria-busy={isLoading || undefined}
          disabled={isLoading}
          className={cn(
            'inline-flex h-10 items-center rounded-md px-4 text-sm font-semibold text-white focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary focus-visible:ring-offset-2 focus-visible:ring-offset-surface disabled:opacity-50',
            destructive ? 'bg-danger hover:opacity-90' : 'bg-primary hover:opacity-90'
          )}
        >
          {confirmLabel}
        </button>
      </div>
    </Modal>
  )
}
